// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDziq1wfNlYNEWmHJJ2w70EEyv4-JeBdPc',
    appId: '1:49134720288:web:908015ad16ad2c46ec3345',
    messagingSenderId: '49134720288',
    projectId: 'iti-flutter-training',
    authDomain: 'iti-flutter-training.firebaseapp.com',
    storageBucket: 'iti-flutter-training.appspot.com',
    measurementId: 'G-M5455LJ2C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfOQKvzQwyjTyx6Xv2AUuaCDDYey1We3w',
    appId: '1:49134720288:android:e02e24bbd9537b10ec3345',
    messagingSenderId: '49134720288',
    projectId: 'iti-flutter-training',
    storageBucket: 'iti-flutter-training.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8qCni9ejQYi5Je9c3xDnBd-hAWVsqBRE',
    appId: '1:49134720288:ios:97087501df778ac4ec3345',
    messagingSenderId: '49134720288',
    projectId: 'iti-flutter-training',
    storageBucket: 'iti-flutter-training.appspot.com',
    iosClientId: '49134720288-nokbhchmgp7r2jp4env5ncp9aalsv714.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
